name: Linux build
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Configure ICU
        run: ./runConfigureICU Linux --enable-static --with-library-bits=64 --prefix=$(pwd)/../
        working-directory: icu/icu4c/source
      - name: Build ICU
        run: make
        working-directory: icu/icu4c/source
      - name: Build ICU include directories
        run: make install
        working-directory: icu/icu4c/source

      - name: Build SDL2
        run: ./configure; make; sudo make install
        working-directory: SDL2
      
      - name: Build SDL2_image
        run: ./configure; make
        working-directory: SDL2_image

      - name: Build SDL2_mixer
        run: ./configure; make
        working-directory: SDL2_mixer

      # Put everything important in include/ and lib/
      - run: mkdir include; mkdir lib
      - run: mv **/include/* include/
      - run: mv **/build/.libs/*.a lib/
      - run: mv **/build/.libs/*.so* lib/
      - run: mv **/.libs/*.a lib/
      - run: mv **/.libs/*.so* lib/
      - run: mv icu/icu4c/include/* include/
      - run: mv icu/icu4c/lib/* lib/

      # Upload everything
      - uses: actions/upload-artifact@v4
        with:
          name: linux-dependencies
          path: |
            include
            lib